[build]
publish = "public/"
command = """
restore_home_cache ".cache" "pip cache" &&
restore_cwd_cache '.venv' 'python virtualenv' &&
pip3 install -q poetry &&
poetry config settings.virtualenvs.in-project true &&
poetry install &&
poetry run statik &&
cp _redirects public/
"""